name: flutter_floating
description: Flutter免权限悬浮窗，支持全局、单页面悬浮，支持边缘吸附、位置保存、上下可滑动区域控制以及屏幕旋转窗口化后的位置修复等。
version: 0.1.4
homepage: https://github.com/LvKang-insist/Floating

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  get: 4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.10
flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.lvkang.floating
    iosBundleIdentifier: com.lvkang.floating
