name: flutter_floating
description: Flutter Permissionless Floating Window, a lightweight, flexible, and fully functional Flutter floating window component.
version: 2.0.0
homepage: https://github.com/kngLv/flutter_floating

environment:
  sdk: ">=2.16.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.10
flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.lvkang.floating
    iosBundleIdentifier: com.lvkang.floating
